// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4OGiSOARXsmfoL-DvrWWviEFPHYMrI0U',
    appId: '1:844831726587:web:5e2be4a4db7b8425c2095e',
    messagingSenderId: '844831726587',
    projectId: 'music-mobile-app-688cc',
    authDomain: 'music-mobile-app-688cc.firebaseapp.com',
    storageBucket: 'music-mobile-app-688cc.firebasestorage.app',
    measurementId: 'G-E1GYKDN1RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbPjrU_DywRMH0zwZTDQMnwUG49MWBw9w',
    appId: '1:844831726587:android:e229c3d95d1028c7c2095e',
    messagingSenderId: '844831726587',
    projectId: 'music-mobile-app-688cc',
    storageBucket: 'music-mobile-app-688cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCLsIayPTFc2zaX6ECe4aElyvRFOXJS4',
    appId: '1:844831726587:ios:fd88f847c2857783c2095e',
    messagingSenderId: '844831726587',
    projectId: 'music-mobile-app-688cc',
    storageBucket: 'music-mobile-app-688cc.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4OGiSOARXsmfoL-DvrWWviEFPHYMrI0U',
    appId: '1:844831726587:web:713ee355ba2624efc2095e',
    messagingSenderId: '844831726587',
    projectId: 'music-mobile-app-688cc',
    authDomain: 'music-mobile-app-688cc.firebaseapp.com',
    storageBucket: 'music-mobile-app-688cc.firebasestorage.app',
    measurementId: 'G-4ZKNVVCLBN',
  );
}
